In [1]:
%reload_ext watermark
%watermark -v -m -p gensim,numpy,scipy,psutil,matplotlib

CPython 3.6.7
IPython 7.6.1

gensim 3.8.0
numpy 1.16.4
scipy 1.3.0
psutil 5.6.3
matplotlib 3.1.1

compiler   : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 18.6.0
machine    : x86_64
processor  : i386
CPU cores  : 4
interpreter: 64bit


In [8]:
import os.path
if not os.path.isfile('text8'):
    !wget -c http://mattmahoney.net/dc/text8.zip
    !unzip text8.zip

--2019-07-27 17:35:05--  http://mattmahoney.net/dc/text8.zip
Resolving mattmahoney.net (mattmahoney.net)... 67.195.197.75
Connecting to mattmahoney.net (mattmahoney.net)|67.195.197.75|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31344016 (30M) [application/zip]
Saving to: ‘text8.zip’

text8.zip           100%[=====================>]  29.89M   702KB/s   in 43s    

2019-07-27 17:35:49 (706 KB/s) - ‘text8.zip’ saved [31344016/31344016]

Archive:  text8.zip
  inflating: text8                   


In [9]:
from gensim.models import Word2Vec, KeyedVectors
from gensim.models.word2vec import Text8Corpus

In [10]:
params = {
    'alpha': 0.05,
    'size': 100,
    'window': 5,
    'iter': 5,
    'min_count': 5,
    'sample': 1e-4,
    'sg': 1,
    'hs': 0,
    'negative': 5
}

model = Word2Vec(Text8Corpus('text8'), **params)
print(model)


Word2Vec(vocab=71290, size=100, alpha=0.05)


In [12]:
# Set up the model and vector that we are using in the comparison
from gensim.similarities.index import AnnoyIndexer

model.init_sims()
annoy_index = AnnoyIndexer(model, 100)


/Users/Devansh/anaconda3/lib/python3.6/site-packages/gensim/similarities/index.py:184: FutureWarning: The default argument for metric will be removed in future version of Annoy. Please pass metric='angular' explicitly.
  index = AnnoyIndex(num_features)


In [13]:
annoy_index

In [40]:
model.wv.syn0norm

/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0norm` (Attribute will be removed in 4.0.0, use self.vectors_norm instead).
  """Entry point for launching an IPython kernel.


array([[-0.00300596, -0.006391  , -0.07924639, ..., -0.03967391,
         0.1249061 ,  0.08720157],
       [-0.01998406,  0.00128089,  0.01750793, ..., -0.03428758,
         0.12492708,  0.08131909],
       [ 0.02480736, -0.05815617, -0.05975022, ..., -0.04756015,
         0.20177244,  0.11985345],
       ...,
       [-0.01783134, -0.06437972,  0.03968306, ..., -0.07265282,
         0.24835244,  0.01834675],
       [ 0.00128116,  0.03286744,  0.04049049, ..., -0.0994527 ,
         0.18000221,  0.10934322],
       [ 0.00412864,  0.07533566, -0.00870231, ..., -0.10259723,
         0.13156658,  0.08406968]], dtype=float32)

In [22]:
# Dry run to make sure both indices are fully in RAM
vector = model.wv.syn0norm[0]
model.most_similar([vector], topn=5, indexer=annoy_index)

/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `syn0norm` (Attribute will be removed in 4.0.0, use self.vectors_norm instead).
  
/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


[('the', 1.0),
 ('in', 0.7141915559768677),
 ('of', 0.7127414047718048),
 ('and', 0.6267342567443848),
 ('which', 0.6131814122200012)]

In [21]:
model.most_similar([vector], topn=5)

/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('the', 1.0),
 ('in', 0.8366272449493408),
 ('of', 0.8349649310112),
 ('a', 0.8157126903533936),
 ('and', 0.7213453054428101)]

In [20]:
vector

array([-0.00300596, -0.006391  , -0.07924639, -0.11311138,  0.16224024,
        0.04311276, -0.1500588 ,  0.07125757, -0.01710221,  0.0422609 ,
        0.11633733, -0.04941724,  0.15095401,  0.1681249 , -0.0437342 ,
        0.07857174, -0.13837984,  0.01057581, -0.13179462, -0.10062777,
        0.05218373, -0.19337521,  0.04304605, -0.09897243, -0.09288712,
        0.07768092,  0.01480838, -0.05771561,  0.04268768,  0.16353555,
       -0.02859131, -0.03882812,  0.03573573,  0.02209255, -0.05305555,
       -0.01947508, -0.00080498, -0.05426248,  0.1182842 , -0.0710705 ,
        0.0900846 , -0.14523095, -0.10871699, -0.13925274, -0.22319958,
       -0.01406333,  0.01283099, -0.11728462, -0.03116909, -0.05302043,
        0.00867285,  0.15445647,  0.4000463 ,  0.0400245 , -0.10233945,
       -0.04841019, -0.0786823 ,  0.10219865,  0.05325449,  0.00943335,
       -0.06226525, -0.05423366, -0.04554814, -0.02641317,  0.11984371,
       -0.0561385 ,  0.026405  ,  0.1669426 ,  0.07914778, -0.01

In [23]:
import time
import numpy as np

In [24]:
def avg_query_time(annoy_index=None, queries=1000):
    """
    Average query time of a most_similar method over 1000 random queries,
    uses annoy if given an indexer
    """
    total_time = 0
    for _ in range(queries):
        rand_vec = model.wv.syn0norm[np.random.randint(0, len(model.wv.vocab))]
        start_time = time.clock()
        model.most_similar([rand_vec], topn=5, indexer=annoy_index)
        total_time += time.clock() - start_time
    return total_time / queries


In [25]:
queries = 10000

gensim_time = avg_query_time(queries=queries)
annoy_time = avg_query_time(annoy_index, queries=queries)
print("Gensim (s/query):\t{0:.5f}".format(gensim_time))
print("Annoy (s/query):\t{0:.5f}".format(annoy_time))
speed_improvement = gensim_time / annoy_time
print ("\nAnnoy is {0:.2f} times faster on average on this particular run".format(speed_improvement))

/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `syn0norm` (Attribute will be removed in 4.0.0, use self.vectors_norm instead).
  
/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  # Remove the CWD from sys.path while we load stuff.


Gensim (s/query):	0.00485
Annoy (s/query):	0.00025

Annoy is 19.45 times faster on average on this particular run


In [28]:
annoy_index = AnnoyIndexer(model, 100)

/Users/Devansh/anaconda3/lib/python3.6/site-packages/gensim/similarities/index.py:184: FutureWarning: The default argument for metric will be removed in future version of Annoy. Please pass metric='angular' explicitly.
  index = AnnoyIndex(num_features)


In [35]:
vector = model["math"]

/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


In [36]:
vector

array([-0.23969483,  0.10536146,  0.3385723 ,  0.34203404,  0.462507  ,
        0.64760506, -0.7498052 ,  0.74991924, -0.43111157,  0.24974273,
       -0.06181143, -0.01704028, -0.23172313,  0.5028631 ,  0.45009816,
        0.54187936, -0.15982251, -0.14826801, -0.35805953,  0.13698873,
        0.03255631,  0.47137672,  0.20513308, -0.5505084 , -0.06536205,
       -0.526175  , -0.36284387, -0.2710168 ,  0.1603922 ,  0.17585874,
        0.51942337, -0.50151825,  0.51363623, -0.22058347, -0.2196507 ,
        0.23919882,  0.23921232, -0.39532056,  0.10240287,  0.41948295,
        0.03189358, -0.5032074 , -0.07620094,  0.05473536,  0.1646023 ,
       -0.1741983 , -0.0783147 ,  0.30044845,  0.07364933,  0.0535882 ,
       -0.3212132 , -0.29868004,  0.7578971 ,  0.17156608, -0.11371195,
       -0.32102096,  0.62634045,  0.1395267 ,  0.17589615,  0.30656812,
        0.18631855,  0.09631731, -0.18147537,  0.05188692, -0.13442856,
        0.08490396,  0.32792637,  0.30371884, -0.1873064 , -0.09

In [37]:
approximate_neighbors = model.most_similar([vector], topn=11, indexer=annoy_index)

/Users/Devansh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


In [38]:
approximate_neighbors

[('math', 0.9998273665114539),
 ('metafont', 0.5770989060401917),
 ('eqworld', 0.5756548643112183),
 ('provers', 0.5675074458122253),
 ('comput', 0.5644209980964661),
 ('bezier', 0.5604610443115234),
 ('mathworks', 0.5602420270442963),
 ('ijcai', 0.5577628314495087),
 ('asc', 0.5566555857658386),
 ('proc', 0.555154949426651),
 ('winograd', 0.5545757114887238)]